#!/usr/bin/env python3
"""Reject private provenance, mutable actions, and publishing authority."""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TEXT_SUFFIXES = {
    "",
    ".json",
    ".md",
    ".py",
    ".rs",
    ".sh",
    ".toml",
    ".tsv",
    ".txt",
    ".yaml",
    ".yml",
}
IGNORED_PARTS = {".git", "__pycache__", "target"}
REQUIRED_POLICY_FILES = {
    ".github/dependabot.yml",
    ".github/workflows/ci.yml",
    ".github/workflows/release.yml",
    ".github/workflows/security.yml",
    "CONTRIBUTING.md",
    "SECURITY.md",
}
PRIVATE_PATTERNS = {
    "private project path": re.compile(
        r"(?<!github\.com/)ajhahnde/|(?:^|[\s/`'\"(])(?:\.agents|\.codex|\.claude)/"
    ),
    "machine-specific user path": re.compile(
        r"(?:/Users/|/home/)[^/\s]+/(?:FlashOS|opaal-transition)\b|"
        r"[A-Za-z]:\\Users\\[^\\\s]+\\(?:FlashOS|opaal-transition)\b"
    ),
    "private backup name": re.compile(r"FlashOS-private-backups|flashos-private-[0-9]"),
    "internal implementation unit": re.compile(r"\b(?:MU|B|T)[0-9]+\b"),
    "internal plan provenance": re.compile(
        r"opaal-identity-version-repository-transition|opaal-transition-(?:public|private)-inventory"
    ),
    "assistance provenance": re.compile(
        r"\b(?:AI[- ]assisted|generated by (?:AI|ChatGPT|Claude|Codex|Gemini)|"
        r"co-authored-by:.*(?:ChatGPT|Claude|Codex|Gemini))\b",
        re.IGNORECASE,
    ),
}
MUTABLE_ACTION = re.compile(r"^\s*-?\s*uses:\s*([^\s#]+)", re.MULTILINE)
FULL_ACTION_PIN = re.compile(r"^[^@\s]+@[0-9a-f]{40}$")
WRITE_PERMISSION = re.compile(r"^\s*[a-z-]+:\s*write\s*(?:#.*)?$", re.MULTILINE)
PUBLISH_COMMAND = re.compile(
    r"\b(?:cargo\s+publish|gh\s+release\s+create|git\s+push|npm\s+publish|"
    r"twine\s+upload)\b"
)


def repository_files(root: Path) -> list[Path]:
    if (root / ".git").exists():
        completed = subprocess.run(
            ["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
            cwd=root,
            capture_output=True,
            check=True,
        )
        paths = [Path(os.fsdecode(item)) for item in completed.stdout.split(b"\0") if item]
    else:
        paths = [path.relative_to(root) for path in root.rglob("*")]
    return sorted(
        (
            path
            for path in paths
            if not any(part in IGNORED_PARTS for part in path.parts)
            and (root / path).is_file()
        ),
        key=Path.as_posix,
    )


def line_number(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def audit(root: Path) -> list[str]:
    problems: list[str] = []
    files = repository_files(root)
    observed = {path.as_posix() for path in files}
    for missing in sorted(REQUIRED_POLICY_FILES - observed):
        problems.append(f"{missing}: missing required standalone policy file")

    for path in files:
        if path.suffix.lower() not in TEXT_SUFFIXES:
            continue
        try:
            text = (root / path).read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue

        is_validator = path in {
            Path("ci/check_public_boundary.py"),
            Path("ci/check_product.py"),
            Path("ci/check_benchmarks.py"),
            Path("ci/tests/test_check_public_boundary.py"),
            Path("ci/tests/test_check_product.py"),
            Path("ci/tests/test_check_benchmarks.py"),
        }
        if not is_validator:
            for label, pattern in PRIVATE_PATTERNS.items():
                for match in pattern.finditer(text):
                    problems.append(
                        f"{path.as_posix()}:{line_number(text, match.start())}: {label}"
                    )

        if path.parts[:2] == (".github", "workflows"):
            if "pull_request_target:" in text:
                problems.append(f"{path.as_posix()}: pull_request_target is forbidden")
            for match in MUTABLE_ACTION.finditer(text):
                action = match.group(1)
                if not action.startswith("./") and not FULL_ACTION_PIN.fullmatch(action):
                    problems.append(
                        f"{path.as_posix()}:{line_number(text, match.start())}: "
                        f"action is not pinned to a full commit SHA: {action}"
                    )
            for match in WRITE_PERMISSION.finditer(text):
                problems.append(
                    f"{path.as_posix()}:{line_number(text, match.start())}: "
                    "workflow write permission is forbidden"
                )
            for match in PUBLISH_COMMAND.finditer(text):
                problems.append(
                    f"{path.as_posix()}:{line_number(text, match.start())}: "
                    "publishing command is forbidden"
                )

    return sorted(set(problems))


def main() -> int:
    problems = audit(ROOT)
    if problems:
        for problem in problems:
            print(problem, file=sys.stderr)
        print(f"public boundary: failed ({len(problems)} findings)", file=sys.stderr)
        return 1
    print(f"public boundary: ok ({len(repository_files(ROOT))} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
